"""add activity source fields

Revision ID: 3ff189ebd15b
Revises: 0b32a44ede02
Create Date: 2026-05-21 14:23:31.266812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff189ebd15b'
down_revision = '0b32a44ede02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=False, server_default='seed'))
        batch_op.add_column(sa.Column('parent_activity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_activities_parent_activity_id', 
            'activities', 
            ['parent_activity_id'], 
            ['id']
        )
        batch_op.create_foreign_key(
            'fk_activities_created_by_user_id', 
            'users', 
            ['created_by_user_id'], 
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_parent_activity_id', type_='foreignkey')
        batch_op.drop_constraint('fk_activities_created_by_user_id', type_='foreignkey')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('parent_activity_id')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
