"""add daily schedule fields to class profile

Revision ID: a8c7e45563e5
Revises: f272a9e62642
Create Date: 2026-05-30 18:00:38.347413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c7e45563e5'
down_revision = 'f272a9e62642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_profiles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('morning_activities', sa.Integer(), nullable=False, server_default='45')
        )
        batch_op.add_column(
            sa.Column('afternoon_activities', sa.Integer(), nullable=False, server_default='30')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('class_profiles', schema=None) as batch_op:
        batch_op.drop_column('afternoon_activities')
        batch_op.drop_column('morning_activities')

    # ### end Alembic commands ###
