"""add planning support fields to activity

Revision ID: f272a9e62642
Revises: 3ff189ebd15b
Create Date: 2026-05-26 01:47:58.811357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f272a9e62642'
down_revision = '3ff189ebd15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_questions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('differentiation_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('family_community_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('learning_outcomes_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('learning_outcomes_summary')
        batch_op.drop_column('family_community_notes')
        batch_op.drop_column('differentiation_notes')
        batch_op.drop_column('assessment_questions')

    # ### end Alembic commands ###
